package pt.ulisboa.tecnico.sec.candeeiros.server;

/* these imported classes are generated by the ping contract */
import pt.ulisboa.tecnico.sec.candeeiros.Ping;
import pt.ulisboa.tecnico.sec.candeeiros.PingServiceGrpc;

import io.grpc.stub.StreamObserver;

public class PingServiceImpl extends PingServiceGrpc.PingServiceImplBase {

	@Override
	public void ping(Ping.PingRequest request, StreamObserver<Ping.PingResponse> responseObserver) {

		// PingRequest has auto-generated toString method that shows its contents
		System.out.println(request);

		// You must use a builder to construct a new Protobuffer object
		Ping.PingResponse response = Ping.PingResponse.newBuilder()
				.setContent(request.getContent()).build();

		// Use responseObserver to send a single response back
		responseObserver.onNext(response);

		// When you are done, you must call onCompleted
		responseObserver.onCompleted();
	}

}
