package pt.ulisboa.tecnico.sec.candeeiros.client;

/* these imported classes are generated by the ping contract */

import com.google.protobuf.ByteString;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import pt.ulisboa.tecnico.sec.candeeiros.Bank;
import pt.ulisboa.tecnico.sec.candeeiros.BankServiceGrpc;
import pt.ulisboa.tecnico.sec.candeeiros.shared.Crypto;

import java.security.*;

public class BankClient {
    private final Logger logger = LoggerFactory.getLogger(BankClient.class);
    private final PublicKey publicKey;
    private final PrivateKey privateKey;
    private final String target;

    public BankClient(String target, String privateKeyFile, String publicKeyFile) {
        this.target = target;
        this.publicKey = (PublicKey) Crypto.readKeyOrExit(publicKeyFile, "pub");
        this.privateKey = (PrivateKey) Crypto.readKeyOrExit(privateKeyFile, "private");
    }

    public static void main(String[] args) {
        // check arguments
        if (args.length < 4) {
            System.err.println("Argument(s) missing!");
            System.err.printf("Usage: java %s host port%n", BankClient.class.getName());
            return;
        }

        final String host = args[0];
        final int port = Integer.parseInt(args[1]);
        final String target = host + ":" + port;

        InteractiveCli cli = new InteractiveCli(target);
        cli.run();
    }
}
